export const data = [
  {
    title: "Radd Portfolio Website",
    id: "1542ADR841",
    desc: "Radd is Portfolio website which is build by React js.",
    imageUrl: "https://i.ibb.co/ZTr69Df/raddportfolio.png",
    url: "https://i.ibb.co/QFtVJ6c/raddportfol.png",
    live_url: "https://earnest-cendol-affc04.netlify.app/",
    description:
      "Radd is Portfolio single page website which is build by React js. In this website implemented dark and light mode option.",
    tools: ["JavaScript", "XML", "CSS", "SASS", "Swiper js", "React Js"],
  },
  {
    title: "Aquasoft Blog website",
    id: "1542ADR842",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    imageUrl: "https://i.ibb.co/P4KrxhR/blog.png",
    url: "https://i.ibb.co/8Y7XBZw/Realstate1.jpg",
    live_url: "https://floating-reaches-03207.herokuapp.com/",
    description:
      "Aquasoft is Blog website which is build for use EJS Template engine",
    tools: ["JavaScript", "ReactJs", "Node Js", "MondoDB", "React-router-dom"],
  },
  {
    title: "TUDO Real estate full-stack development",
    id: "1542ADR843",
    desc: "Real estate buying and selling website frontend development",
    imageUrl: "https://i.ibb.co/3kVZhZ6/realestate.png",
    url: "https://i.ibb.co/8Y7XBZw/Realstate1.jpg",
    live_url: "https://tudo-realestate.netlify.app/",
    description:
      "TUDO-Real estate is a property buy sell full-stack web-application which build by React Js and building duration (15-Nov-2021 to 23-Dec-2021). Organized an attractive responsive user interface implemented by React Js.      • Utilize Property details page and user place order from this section.      • Constructed User panel and with dynamic data loaded from MongoDB server",
    tools: ["JavaScript", "ReactJs", "Node Js", "MondoDB", "React-router-dom"],
  },
  {
    title: "Lookouts ecommerce frontend development",
    id: "1542ADR844",
    desc: "Lookouts ecommerce is a landing page development using React Js",
    imageUrl: "https://i.ibb.co/j6BMM5S/ecommerce2.jpg",
    url: "https://i.ibb.co/bJ9q7CT/lookouts.png",
    live_url: "https://lookouts-shop.netlify.app/",
    description: "",
    tools: [
      "JavaScript",
      "ReactJs",
      "Node Js",
      "MondoDB",
      "Tailwind CSS",
      "Swiper Js",
      "Reval Js",
      "React-router-dom",
      "Firebase",
    ],
  },
  {
    title: "TUDO full-stack ecommerce development",
    id: "1542ADR845",
    desc: "Full-Stack Ecommerce website. It's focused on ecommerce all functionality.",
    imageUrl: "https://i.ibb.co/xHZcppg/ec.png",
    url: "https://i.ibb.co/St7g4RV/ec.png",
    live_url: "https://tudo-ecommerce-project.herokuapp.com/",

    description:
      "TUDO-eCommerce is a full stack ecommerce application which build by React Js and building duration (29-Jan-2022 to 03-Mar-2022). Implemented beautiful users interface use SCSS with external styling library and used MaterialUI component to manage dashboard easily. This application contains many types of functionality such as User account (user can register and login here), user can place an order with follow some steps. Here install stripe payment gateway for credit-card. After placed order user can see this order status this order is accepted or on the way or delivered. Note after placed order user can send a request to cancel order. A user can change their email, password, avatar, etc. User can give review on a product. Build API authentication using encrypted methodology with employed privet route user and admin. Without login user cannot enter their profile route.   Developed admin panel with CRUD operation with eCommerce full functionality like admin can manage all user, all order, all products and all reviews, etc. Admin can see their earnings, stocked and stock out product list, etc. ",
    tools: [
      "JavaScript",
      "ReactJs",
      "Node Js",
      "MondoDB",
      "React-router-dom",
      "MaterialUI",
      "SCSS",
      "Express Js",
      "Postman",
      "JWT",
      "Cookie",
      "Stripe",
    ],
  },
  {
    title: "NFPort is a Boat Booking dashboard",
    id: "1542ADR846",
    desc: "NFPort is a Boat Booking dashboard it's boat booking system.",
    imageUrl: "https://i.ibb.co/VShWDxs/nfpoart.png",
    url: "https://i.ibb.co/VShWDxs/nfpoart.png",
    live_url: "https://gorgeous-tartufo-fb557b.netlify.app/",
    description:
      "NFPort is a Boat Booking dashboard only for frontend development with dummy data. In this website contain twelve pages, which has developed by React Js and SASS with some supporting library.",
    tools: ["JavaScript", "XML", "CSS", "SASS", "Swiper js", "React Js"],
  },
  {
    title: "NFBoat is a Boat Booking app.",
    id: "1542ADR847",
    desc: "NFBoat is a Boat Booking client site website it's boat booking system.",
    imageUrl: "https://i.ibb.co/SX83tLn/nfboat-2.png",
    url: "https://i.ibb.co/FHJ9z9k/nfboat-1.png",
    live_url: "https://roaring-chimera-5ee6fa.netlify.app/",
    description:
      "NFBoat is a Boat Booking client side website it's only for frontend development with dummy data. In this website contain twenty two pages, which has developed by React Js and SASS with some supporting library.",
    tools: ["JavaScript", "XML", "CSS", "SASS", "Swiper js", "React Js"],
  },
  {
    title: "Radd Agency Website.",
    id: "1542ADR848",
    desc: "Radd is demo Digital agency website developed by React Js.",
    imageUrl: "https://i.ibb.co/Mg0vRQS/radd12.png",
    url: "https://i.ibb.co/GCYg7t7/radd1.png",
    live_url: "https://lustrous-shortbread-7c8181.netlify.app/",
    description: "",
    tools: ["JavaScript", "XML", "CSS", "SASS", "Swiper js", "React Js"],
  },

  {
    title: "Crypto landing page development",
    id: "1542ADR84",
    desc: "Crypto Landing page psd to HTML CSS and JS Development",
    imageUrl: "https://i.ibb.co/q9KkVSS/crypto-Copy.png",
    url: "https://i.ibb.co/q9KkVSS/crypto-Copy.png",
    description:
      "This crypto landing page development is a just psd to HTML converting work. I did for my client.",
    tools: ["JavaScript", "HTML", "CSS"],
  },
];
